language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch

# command to install dependencies
install:
    - git clone https://github.com/blockchain/api-v1-client-python
    - cd api-v1-client-python
    - python setup.py install

# command to run tests
script: nosetests
