language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch

# Turning email notifications off
notifications:
  email: false

# command to install dependencies
install:
    - pip install requests
    - pip install matplotlib

# command to run tests
script: nosetests
