language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch

# command to install dependencies
install:
    - pip install .
    - pip install -r requirements.txt
    - pip install blockchain
# command to run tests
